name = "BioPipelines"
uuid = "3ee1394b-c0b4-492e-bb3c-d8bc89983562"
authors = ["Jiacheng Chuan <jiacheng_chuan@outlook.com>"]
version = "0.1.0"

[deps]
Pipelines = "ef544631-5c6f-4e9b-994c-12e7a4cd724c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
