#!Rscript

if (is.na(packageDescription("taxonomizr")[1])) install.packages("taxonomizr")
if (is.na(packageDescription("argparse")[1])) install.packages("argparse")
if (is.na(packageDescription("stringr")[1])) install.packages("stringr")

library(taxonomizr, quietly = T)
library(argparse, quietly = T)
library(stringr, quietly = T)

### parsing arguments
parser <- ArgumentParser(description='Input a table file which has an NCBI Accession column. Query taxonomy locally, and add the results to the table.')
parser$add_argument('-i', '--input', dest='input', metavar='FILE', type='character',
                    required=TRUE, nargs='+',
                    help='[REQUIRED] input tsv files generated by CLC BLAST module, or blastn (`blastn -outfmt 7`)')
parser$add_argument('-c', '--accession-column', dest='accession-column', metavar='COL', type='character',
                    default=4,
                    help='the column index of Accession ID used for querying NCBI. If input is generated from blastn -outfmt 7, auto detect')
parser$add_argument('-d', '--db', dest='db', metavar='db', type='character',
                    required=TRUE,
                    help='taxonomizr SQLite database')
parser$add_argument('-o', '--output', dest='output', metavar='TSV', type='character',
                    default="<input>.lineage.tsv",
                    help='output lineage file (default: <input>.lineage.tsv)')

args <- parser$parse_args()

db <- args$db
inputs <- args$input
accession_col <- args$`accession-column`

for (input in inputs){
    
    out <- str_replace_all(args$output, "<input>", input)
    
    nline <- system(str_interp("wc -l ${input} | awk '{print $1}' "), intern = TRUE)
    if (nline == "0") {
        # input is empty
        writeLines(str_interp("Accession2Taxonomy: input is empty: ${input}"))
        system(str_interp("truncate --size=0 ${out}"))
        next
    }

    fields_line <- system(str_interp("head -n 5 ${input} | grep '^# Fields: ' "), intern = TRUE)

    if (length(fields_line) == 0) {
        # not results from blastn -outfmt 7
        dt <- read.delim(input, header = F, comment.char = '#')
        accession_col_auto <- accession_col

    } else {
        fields <- str_split(str_remove(fields_line, "# Fields: "), ", ")[[1]]
        dt <- read.delim(input, header = F, col.names = fields, check.names = FALSE, comment.char = '#')
        accession_col_auto <- which("subject acc.ver" == fields)
        if (length(accession_col_auto) == 0) {
            warning(str_interp("Cannot detect the accession column automatically: 'subject acc.ver' not found. Use --accession-column ${accession_col} instead for input file: ${input}"))
            accession_col_auto <- accession_col
        }
    }

    ids <- accessionToTaxa(dt[[accession_col_auto]], db)
    taxs <- getTaxonomy(ids, db, desiredTaxa = c("superkingdom", "clade", "phylum", "class", "order", "family", "genus", "species", "subspecies", "strain"))
    dt <- cbind(dt, as.data.frame(taxs))
    write.table(dt, out, quote = F, sep = '\t', row.names = F)
    writeLines(str_interp("Accession2Taxonomy: output: ${out}"))
}
